### PR TITLE
Completed Feature: Image Size Threshold (Issue : #3) 

### PR DESCRIPTION
**Pull request by deexithparand**
Here's a revised version of your PR description:

---

### PR Description

- [x] **Main Feature:** Implemented `RemoveExceedSizeLimit()` to address the image size threshold for clearing unused images.
- [x] **Code Refactor 01:** Replaced `log.Fatalf` with `log.Printf` to improve error handling by returning errors to `main.go`. Additionally, added `utils.go` in the Docker package to consolidate reusable functions.
- [x] **Code Refactor 02:** Removed all `fmt` package usages and switched to the Go `log` library for logging.

### Testing

dockclean-sizelimit

--- 

Let me know if you need any more adjustments!

### CODE REVIEW

**Comment by deexithparand** [comment]
Hi @mmuazam98, I have completed the Issue #3 also which has been assigned to me. Could you please review and merge this if it looks good.

I'll complete the goroutines issue #6 and update you soon

Thanks

**Comment by deexithparand** [comment]
Hi @mmuazam98 , could you also add hacktoberfest-accepted label after merging this PR. 

To make it valid for Hacktoberfest 

Thanks!

**Comment by mmuazam98** [comment]
@deexithparand can you create a new PR that updates the README file?

**Comment by deexithparand** [comment]
Sure @mmuazam98 , I'll raise a new PR and update the README

**Pull request merged**
